name: medsyn-3-8
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2024.3.11=h06a4308_0
  - comm=0.2.1=py38h06a4308_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - ipykernel=6.28.0=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.5.0=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - openssl=3.0.13=h7f8727e_1
  - packaging=23.2=py38h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.0=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - python=3.8.19=h955ad1f_0
  - python-dateutil=2.9.0post0=py38h06a4308_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.3.3=py38h5eee18b_0
  - traitlets=5.7.1=py38h06a4308_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.30.1
      - beartype==0.18.5
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - diffusers==0.27.2
      - einops==0.8.0
      - einops-exts==0.0.4
      - filelock==3.14.0
      - fsspec==2024.5.0
      - huggingface-hub==0.23.0
      - idna==3.7
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - monai==0.8.1
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - pillow==10.3.0
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.31.0
      - rotary-embedding-torch==0.6.1
      - safetensors==0.4.3
      - simpleitk==2.3.1
      - sympy==1.12
      - tokenizers==0.19.1
      - torch==2.3.0
      - torchaudio==2.3.0
      - torchtext==0.18.0
      - torchvision==0.18.0
      - tqdm==4.66.4
      - transformers==4.40.2
      - triton==2.3.0
      - urllib3==2.2.1
      - xformers==0.0.26.post1

